<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "team".
 *
 * @property int $id
 * @property string $name
 *
 * @property PartyTeam[] $partyTeams
 */
class Team extends \yii\db\ActiveRecord
{
    public $teams;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'team';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 1000],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'teamsList' => 'Команды',
        ];
    }

    /**
     * Gets query for [[PartyTeams]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPartyTeams()
    {
        return $this->hasMany(PartyTeam::className(), ['team_id' => 'id']);
    }

    public function getTeamsList()
    {
        $teams = PartyTeam::find()->where(['team_id' => $this->id])->all();
        $result = "";
        foreach ($teams as $team)
            $result .= '<b><font style="color: '.$team->color->code.'">'.$team->team_name.'</font></b> ('.$team->color->name.')<br>';
        return $result;
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($this->teams !== null && $this->teams[0]->team_name !== "")
        {
            foreach ($this->teams as $team)
            {
                $newTeam = new PartyTeam();
                $newTeam->color_id = $team->color_id;
                $newTeam->team_name = $team->team_name;
                $newTeam->team_id = $this->id;
                $newTeam->save();
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        $pts = PartyTeam::find()->where(['team_id' => $this->id])->all();
        foreach ($pts as $pt) $pt->delete();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
